name: "test"

on: push

jobs:
  test:
    name: "Unit tests"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        deno-version: [10.0.139.17]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Test Deno Module
        run: deno test --allow-none
